In [1]:
pip install transformers torch pandas accelerate sentencepiece

Requirement already satisfied: transformers in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (4.44.2)
Requirement already satisfied: torch in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (2.5.1+cu121)
Requirement already satisfied: pandas in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (2.0.3)
Requirement already satisfied: accelerate in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (0.33.0)
Requirement already satisfied: sentencepiece in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (0.1.99)
Requirement already satisfied: filelock in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from transformers) (3.19.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from transformers) (0.24.7)
Requirement already satisfied: numpy>=1.17 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from transformers) (2026.1.15)
Requirement already satisfied: requests in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from transformers) (2.32.5)
Requirement already satisfied: safetensors>=0.4.1 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from transformers) (0.7.0)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from transformers) (0.19.1)
Requirement already satisfied: tqdm>=4.27 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from transformers) (4.68.2)
Requirement already satisfied: fsspec>=2023.5.0 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from huggingface-hub<1.0,>=0.23.2->transformers) (2025.10.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from huggingface-hub<1.0,>=0.23.2->transformers) (4.15.0)
Requirement already satisfied: networkx in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from torch) (3.2.1)
Requirement already satisfied: jinja2 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from torch) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from torch) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from torch) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from torch) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from torch) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from torch) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from torch) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from torch) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from torch) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from torch) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from torch) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from torch) (12.1.105)
Requirement already satisfied: triton==3.1.0 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from torch) (3.1.0)
Requirement already satisfied: sympy==1.13.1 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from torch) (1.13.1)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch) (12.4.127)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.1 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from pandas) (2025.3)
Requirement already satisfied: psutil in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from accelerate) (5.9.5)
Requirement already satisfied: six>=1.5 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from requests->transformers) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from requests->transformers) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from requests->transformers) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in /mnt/Data/yashv7523/anaconda3/lib/python3.9/site-packages (from requests->transformers) (2026.5.20)
WARNING: Error parsing dependencies of pytorch-lightning: .* suffix can only be used with `==` or `!=` operators
    torch (>=1.7.*)
           ~~~~~~^
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

In [2]:
MODEL_NAME = "Qwen/Qwen2.5-7B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME,
    trust_remote_code=True
)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16,
    device_map="auto",
    trust_remote_code=True
)

print("Model Loaded Successfully")

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/663 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading shards:   0%|          | 0/4 [00:00<?, ?it/s]

model-00001-of-00004.safetensors:   0%|          | 0.00/3.95G [00:00<?, ?B/s]

model-00002-of-00004.safetensors:   0%|          | 0.00/3.86G [00:00<?, ?B/s]

model-00003-of-00004.safetensors:   0%|          | 0.00/3.86G [00:00<?, ?B/s]

model-00004-of-00004.safetensors:   0%|          | 0.00/3.56G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/243 [00:00<?, ?B/s]

Model Loaded Successfully

In [3]:
df = pd.read_excel("Allahabad_criminal_merged.xlsx")

print("Dataset Shape:", df.shape)

df.head()

Dataset Shape: (199, 10)

,case_id,language,case_type,judgment_text,subject,object,objective_aspect,subjective_aspect,reasoning,legal provision
0,ALL_CRIM_000001,Hindi,Criminal,Court No.=27\n\nAPPLICATION UIS 482 No. - 741 ...,Dinesh Yadav @ Dinesh Kumar And 7 Others,Wife/Complainant,Assault; Bigamy; Cruelty; Intentional Insult; ...,Dowry Demand,NaN,NaN
1,ALL_CRIM_000002,Hindi,Criminal,‘Neutral Citation No. - 2023:AHC:145371\n\nCou...,Kamlesh Jaiswal Alias Monu Jaiswal And Another,State/Society,Criminal Law Amendment Act Offence,Not Clearly Specified,NaN,NaN
2,ALL_CRIM_000003,Hindi,Criminal,‘Neutral Citation No. - 2024:AHC-LKO:1629\nCou...,Bahal Khan And 4 Others,Complainant/Informant,Rioting; Rioting With Deadly Weapon; Assault; ...,Intent/Knowledge To Cause Death Or Serious Harm,NaN,NaN
3,ALL_CRIM_000004,Hindi,Criminal,"Court No, -27\n(Case := APPLICATION U/S 482 No...",Banshi Lal,Complainant/Informant,Kidnapping Or Abduction,Intent To Compel Wrongful Restraint/Confinement,NaN,NaN
4,ALL_CRIM_000005,Hindi,Criminal,Neutral Citation No. - 2024:AHC-LKO:7688\nCour...,Mohd. Mahfooz,Wife/Complainant,Assault; Mischief; Cruelty; Intentional Insult,Dowry Demand,NaN,NaN

In [4]:
sample_df = df.head(5).copy()

print("Records Selected:", len(sample_df))

Records Selected: 5

In [19]:
sample_df
len(sample_df.loc[0, "judgment_text"])

2275

In [11]:
def build_prompt(row):

    return f"""
You are an expert Indian legal reasoning assistant.

Your task is to generate a concise explanation of the court's final reasoning and outcome based only on the judgment.

Judgment:
{row['judgment_text']}

Instructions:
1. Focus primarily on the court's final reasoning and outcome.
2. Explain why the court allowed, dismissed, quashed, granted bail, rejected bail, convicted, acquitted, or otherwise disposed of the case.
3. Base the explanation only on the reasoning contained in the judgment.
4. Do not merely restate allegations from the FIR or procedural history unless they are necessary to explain the court's reasoning.
5. Do not hallucinate or introduce legal facts not present in the judgment.
6. Write 4-8 clear and coherent sentences.

Output only the reasoning text.
"""

In [12]:
prompt = build_prompt(sample_df.iloc[0])

print(prompt[:3000])

You are an expert Indian legal reasoning assistant.

Your task is to generate a concise explanation of the court's final reasoning and outcome based only on the judgment.

Judgment:
Court No.=27

APPLICATION UIS 482 No. - 741 of 2024





Applicant :- Dinesh Yadav @ Dinesh Kumar And 7 Others
Opposite Party :- State Of U.P. Thru, Prin, Secy. Home Deptt. Lko. And
Another

Counsel for Applicant
Yadav

Counsel for Opposite Party



Santosh Kumar Srivastava Subhash Chandra

GAL



‘Hon‘ble Subhash Vidyarthi,J.

1. प्रार्थीगण के विद्वान अधिवक्ता श्री संतोष कुमार श्रीवास्तव , विद्वान अतिरिक्त
शासकीय अधिवक्ता श्री राकेश कुमार सिंह तथा विपक्षी संख्या 2 के विद्वान अधिवक्ता
श्री सुभाष चन्द्र यादव को सुना तथा पत्रावली का अवलोकन किया।



2. धारा 482 दण्ड प्रक्रिया संहिता के अन्तर्गत प्रस्तुत इस प्रार्थना पत्र द्वार प्राथीगण ने
प्रथम सूचना रिपोर्ट संख्या 451 सन 2019 अन्तर्गत RT 923, 494, 498-A,
504, 506 भाठदं०सं० थाना विभूति खण्ड जनपद लखनऊ के अमुक्रम में प्रस्तुत
आरोप पत्र दिनांकित 16.6.2020 जिसमें प्रार्थी संख्या 1 को धारा 323, 494,
498-A, 504, 506 भा०दं०सं० एवं प्रा्थी संख्या 2 से 8 को घारा 323, 498-
8, 504, 506 भा०दं०सं० के आरोपों से आरोपित किया गया है तथा उक्त के
आधार पर आपराधिक वाद संख्या 15493 सन 2021, जो कि विद्वान मुख्य
न्यायिक मजिस्ट्रेट, लखनऊ के न्यायालय में लंबित है, के निरस्तीकरण की प्रार्थना
इस आधार पर की गई है कि पक्षों के मध्य समझौता हो गया है।

3. इसके पूर्व प्राथीण ने इस न्यायालय के समक्ष घारा 482 दं०प्र०्सं० के अंतर्गत
प्रा्थना-पत्र संख्या 10378 सन 2023 प्रस्तुत किया था जो दिनांक 19.10.2023
को इस निर्देश के साथ निस्तारित हुआ कि सुलहनामा को विचारण न्यायालय द्वारा
सत्यापित किया जाये।

4. विचारण न्यायालय ने सुलहनामा को दिनांक 07.12.2023 के आदेश द्वारा
सत्यापित कर दिया।
_x000C_
5. विपक्षी संख्या 2 के विद्वान अधिवक्ता श्री सुभाष चन्द्र यादव ने प्रार्थना -पत्र का
समर्थन किया।

6. तदनुसार, प्रार्थना पत्र स्वीकार किया जाता है। प्रथम सूचना रिपोर्ट संख्या 451
सन 2019 अन्तर्गत धारा 323, 494, 498-8, 504, 506 भा०दं०सं० थाना
विभूति खण्ड जनपद लखनऊ के अमुक्रम में प्रस्तुत आरोप पत्र दिनांकित
16.6.2020 जिसमें प्रा्थी संख्या 1 को धारा 323, 494, 498-8, 504, 506
भा०दं०सं० एवं प्रार्थी संख्या 2 से 8 को धारा 323, 498-8, 504, 506
भा०दं०सं० के आरोपों से आरोपित किया गया है तथा उक्त के आधार पर आपराधिक
वाद संख्या 15493 सन 2021, जो कि विद्वान मुख्य न्यायिक मजिस्ट्रेट, लखनऊ
के न्यायालय में लंबित है, तथा उपरोक्त आपराधिक वाद की संपूर्ण कार्यवाही प्रा्थीगण
के विरुद्ध निरस्त की जाती है।

(Subhash Vidyarthi,3.)

Order Date
Ankit

30.1.2024

Instructions:
1. Focus primarily on the court's final reasoning and outcome.
2. Explain why the court allowed, dismissed, quashed, granted bail, rejected bail, convicted, acquitted, or otherwise disposed of the case.
3. Base the explanation only on the reasoning contained in the judgment.
4. Do not merely restate allegations from the FIR or procedural history unless they are necessary to explain the court's reasoning.
5. Do not hallucinate or introduce legal facts not present in the judgment.
6. Write 4-8 clear and coherent sentences.

In [13]:
row = sample_df.iloc[0]

prompt = build_prompt(row)

messages = [
    {
        "role": "system",
        "content": "You are a legal reasoning expert."
    },
    {
        "role": "user",
        "content": prompt
    }
]

text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)

inputs = tokenizer(
    text,
    return_tensors="pt"
).to(model.device)

outputs = model.generate(
    **inputs,
    max_new_tokens=300,
    temperature=0.3,
    top_p=0.9,
    do_sample=True
)

response = tokenizer.decode(
    outputs[0][inputs.input_ids.shape[1]:],
    skip_special_tokens=True
)

print(response)

The court allowed the application under Section 482 CrPC as the parties had reached a settlement through a reconciliation deed, which was affirmed by the trial court on December 7, 2023. Consequently, the prosecution against the applicants under Sections 323, 494, 498A, 504, and 506 of the Indian Penal Code in Case No. 15493/2021 before the Principal Magistrate, Lucknow, was quashed.

In [14]:
generated_reasonings = []

for idx, row in sample_df.iterrows():

    prompt = build_prompt(row)

    messages = [
        {
            "role": "system",
            "content": "You are a legal reasoning expert."
        },
        {
            "role": "user",
            "content": prompt
        }
    ]

    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(
        text,
        return_tensors="pt"
    ).to(model.device)

    outputs = model.generate(
        **inputs,
        max_new_tokens=300,
        temperature=0.3,
        top_p=0.9,
        do_sample=True
    )

    response = tokenizer.decode(
        outputs[0][inputs.input_ids.shape[1]:],
        skip_special_tokens=True
    )

    generated_reasonings.append(response)

    print("="*100)
    print(f"CASE {idx}")
    print(response)
    print()

====================================================================================================
CASE 0
The court allowed the application under Section 482 CrPC as the parties had reached a mutual settlement as evidenced by the reconciliation deed which was affirmed by the judicial magistrate. The court dismissed the criminal charges against the applicants based on the reconciliation deed and the subsequent affirmation by the judicial magistrate.

====================================================================================================
CASE 1
The court allowed the anticipatory bail application after considering the arguments presented by the learned advocate for the applicant. The court found that the accused had not committed any offense as alleged and was not guilty of the charges framed against him. The court also noted that the accused had no criminal history and no interest against him in the case. Consequently, the court directed that if the applicant surrenders and submits to bail, his bail application would be considered by the High Court in accordance with the procedure laid down in Satendra Kumar Antil vs. Central Bureau of Investigation and another (Special Leave to Appeal Crl) No. 5191 of 2021. As a result, the application was finally dismissed in its current form but with the condition mentioned.

====================================================================================================
CASE 2
The court allowed the application under Section 482 of the CrPC as the parties had reached a settlement through a mutual agreement on December 14, 2023. Since more than five years had passed without the trial court being impeded, and considering that the parties have now reconciled and no further criminal proceedings are desired by the opposite party, the court found it appropriate to terminate the criminal proceedings initiated against the applicants.

====================================================================================================
CASE 3
Based on the evidence and arguments presented, the court found that the accused individual denied committing the offense, other witnesses also contradicted the statements made in the first information report, and the alleged victim had passed away. Considering all the facts and circumstances, the court concluded that there was no valid legal challenge to the impugned orders. Therefore, the application under Section 482 was dismissed.

====================================================================================================
CASE 4
The court allowed the application under Section 482 of the Criminal Procedure Code. It accepted the mutual agreement reached on November 10, 2023, between the parties, as evidenced by the affidavit annexed to the application. The court concluded that the prosecution against the applicant should be withdrawn based on this agreement.

In [16]:
sample_df["reasoning"] = generated_reasonings

sample_df[
    [
        "case_id",
        "subject",
        "object",
        "reasoning"
    ]
].head()

,case_id,subject,object,reasoning
0,ALL_CRIM_000001,Dinesh Yadav @ Dinesh Kumar And 7 Others,Wife/Complainant,The court allowed the application under Sectio...
1,ALL_CRIM_000002,Kamlesh Jaiswal Alias Monu Jaiswal And Another,State/Society,The court allowed the anticipatory bail applic...
2,ALL_CRIM_000003,Bahal Khan And 4 Others,Complainant/Informant,The court allowed the application under Sectio...
3,ALL_CRIM_000004,Banshi Lal,Complainant/Informant,"Based on the evidence and arguments presented,..."
4,ALL_CRIM_000005,Mohd. Mahfooz,Wife/Complainant,The court allowed the application under Sectio...

In [17]:
sample_df.to_csv(
    "Allahabad_criminal_reasoning_sample.csv",
    index=False
)

print("Saved Successfully")

Saved Successfully